### ISSUE TITLE
Missing typescript declaration file

### ISSUE THREAD

**Issue by techmunk** [gajus/http-terminator#1]
Hi,
Would love to try this module out. It's however missing a typescript declaration file which makes it a no go for me at the moment. Would you consider adding one?

**Comment by gajus** [comment]
Use typedef.

**Comment by cinderblock** [comment]
Are you talking about this? https://jsdoc.app/tags-typedef.html

This is a far cry from TypeScript types that are the de facto standard these days.

Would you consider a PR that adds TypeScript `types`?

**Comment by cinderblock** [comment]
Well, since the answer is "no", for those that want TypeScript, I've forked a version. I'm also moving to Jest for testing. https://github.com/cinderblock/http-terminator/

**Comment by joebowbeer** [comment]
I guess someone will need to push these to DefinitelyTyped
