### ISSUE TITLE
importing createHttpTerminator with ES modules

### ISSUE THREAD

**Issue by FlorianMuller** [gajus/http-terminator#12]
Hi,
when creating a node.js project with `"type": "module"` in it's `package.json` to use [ES modules](https://nodejs.org/api/esm.html#esm_package_json_type_field) (and use `import` / `export` syntax), the import of `createHttpTerminator` like this:

```node
// importing createHttpTerminator like the doc
import {
  createHttpTerminator,
} from 'http-terminator';
```

throw this error:
```
SyntaxError: The requested module 'http-terminator' does not provide an export named 'createHttpTerminator'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

To bypass this, I must import `http-terminator` like that:
```node
import httpTerminator from 'http-terminator';
const { createHttpTerminator } = httpTerminator;
```

Seems like there's only a default export and no named export.

**Comment by euclid1990** [comment]
@FlorianMuller I have same issue with "type": "module"` in it's `package.json` to use [ES modules].
I have fixed it by using:
```js
import httpTerminator from 'http-terminator'
...
const serverTerminator = httpTerminator.createHttpTerminator({ server })
```

**Comment by gajus** [comment]
https://github.com/gajus/http-terminator/blob/71152044aa9297b843ceb7aab1440381673ed20e/src/index.js#L3

We are exporting `createHttpTerminator`. If there is an issue with Babel transpilation, that should be raised with them.

**Comment by FlorianMuller** [comment]
There can't be an issue with Babel because I'm not using it.

Node now directly support the ecmascript [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) syntax (without babel) if your file extension end in `.mjs` or if the nearest parent `package.json` file contains a `"type"` field with the value `"module"` (that's my case 👋🏻). ([more details here](https://nodejs.org/api/esm.html#esm_enabling))

I think your named import works with babel but not with the node support for ecmascript module.

You should maybe try to resolve this or change the documentation to not use named import in the exemple (or maybe precise that babel is needed to do that type of import ? 🤷🏻‍♂️).

**Comment by gajus** [comment]
> There can't be an issue with Babel because I'm not using it.

Babel is used to compile this library.
