### ISSUE TITLE
Call a cleanup function after all all connections are closed

### ISSUE THREAD

**Issue by amit777** [gajus/http-terminator#13]
Hi, I was wondering if there is an easy way to call a cleanup function once all the connections are closed.

Also, I wasn't quite clear what the difference between using this module vs server.close() is.  Am I correct in understanding that this library does the business of closing persistent connections which server.close() does not?

Thanks for creating this!

**Comment by gajus** [comment]
`terminate` returns a promise, so you can just do clean up after it resolves:

```js
await httpTerminator.terminate();

// do you clean up here

```

> Am I correct in understanding that this library does the business of closing persistent connections which server.close() does not?

Yes.
