### ISSUE TITLE
Close immediately after requests are done

### ISSUE THREAD

**Issue by ErisDS** [gajus/http-terminator#16]
In the readme it states that http-terminator should wait for requests to finish before closing connections.

As far as I can tell, if http-terminator is set to have a long timeout, and has to handle a long-running request. It actually doesn't close until the timeout ends, even if all the requests have finished.

Reproduce:

- Setup a little express app with 2 endpoints:

```
app.get('/', (req, res) => res.send('Hello World!'));
app.get('/long', (req, res) => {
    setTimeout(function () {
        res.status(200).send('Done long request');
    }, 10000);
});
```

- Make sure to start your server something like this:

```
 setInterval(() => this.server.getConnections(
         (err, connections) => console.log(`${connections} connections currently open`)
), 3000);

 this.httpTerminator = createHttpTerminator({
     server: this.server,
     gracefulTerminationTimeout: 60000
});

process.on('SIGINT', function () {
     this.httpTerminator.terminate();
}
```

Now to test:

- Run your app. 
- make a request to the homepage
- Ctrl + c / send SIGINT

See the server closes immediately

- Run your app. 
- make a request to the /long
- Ctrl + c / send SIGINT
- Watch the connections get closed until there is 1 left
- Note the open request finishes after 10000ms, now there are 0 connections

See the server doesn't close for a very long time.

I would expect that the server would close as soon as the conditions that there are 0 connections and the last request is finished are met OR after 60000ms, whichever is first.

**Comment by ErisDS** [comment]
Note: I just ran the same test with stoppable, and it closes once the last request finishes. Obviously it has other issues though :)

**Comment by gajus** [comment]
Hey, thanks for reporting this – are you available to PR either a failing test case or a fix + test?

**Comment by ErisDS** [comment]
I can provide access to my demo code that shows this library and stoppable don't do the same thing later today. 

I did have a look at the tests and the code to see what I could do, but it's tricky to grasp quickly.

As far as I can tell the first test here https://github.com/gajus/http-terminator/blob/master/test/helpers/createTests.js#L38 is what should be testing this case, but it doesn't include testing that the server closes. I can't see any test with a strategy for testing that the server closes?

If you can point me in the direction of the pattern/strategy you would use for that, I can probably work from there.

**Comment by ErisDS** [comment]
Also just to add - the code doesn't have much in the way of comments except "// $FlowFixMe" which I don't understand?

**Comment by ErisDS** [comment]
Should I share my demo code?

**Comment by jylauril** [comment]
I'm having the same problem with a very basic setup. Didn't have this problem with stoppable.

I tested changing my code to just call the `server.close` instead of the `httpTerminator.terminate` and that worked much better. I did notice that after enough manual hard restarts (killing the process manually), it suddenly started working for a while but went back to hanging state after X amount of restarts.

That makes this really hard to debug, so I might just switch back to stoppable to get going again.

**Comment by amit777** [comment]
@jylauril i'm researching this lib vs stoppable.  Curious what made you look for a different lib than stoppable?

**Comment by jylauril** [comment]
@amit777 there was an issue that the author of this lib had posted on stoppable: https://github.com/hunterloftis/stoppable/issues/25

The two problems I have with stoppable are the fact that stoppable monkey-patches the http-server instance, and second problem is that the library is not really actively maintained (last actual change was 2 years ago)

**Comment by ErisDS** [comment]
I only looked at http-terminator because of the issue that the author of this lib wrote on stoppable.

Monkey patching isn't ideal, but stoppable does work correctly, whereas http-terminator has this bug. 

Ghost is using stoppable in production now and has been for about a month without issue.

One of the final deciding factors for me was that the code in stoppable even though not well maintained is easier to follow. I couldn't see how to fix the bug in http-terminator and as the author didn't reply to my questions, I think we can conclude that http-terminator is not better maintained it's just newer and less well-battle tested & that the issue raised on stoppable is a bit cheeky/premature 😬

**Comment by gajus** [comment]
Thanks Eris for your input, but the conversation is derailing.

Valuable contributions at this point are:

* a test case that is failing (not a link to your demo)
* a test case with a fix

Beyond this, the bug has been described and acknowledged.
