### ISSUE TITLE
Bundle size increased from 18.6 kB to  819.7 kB between v2.0.3 and v3.0.0

### ISSUE THREAD

**Issue by michael-wolfenden** [gajus/http-terminator#28]
I believe the large bundle size comes from the dependency on [roarr](https://bundlephobia.com/package/roarr@4.0.11)

You can see the bundle size differences between the versions at:
[https://bundlephobia.com/package/http-terminator@3.0.0](https://bundlephobia.com/package/http-terminator@3.0.0)

**Comment by gajus** [comment]
It does not seem like roarr is the culprit.

https://bundlephobia.com/package/roarr@7.0.3

Either way, this is a server side package. No plans to optimize the dependency size.

**Comment by michael-wolfenden** [comment]
@gajus that's not the version of roarr that this library is using. It looks like they have made improvements to their bundle size, would you consider upgrading to the lastest version. I'm currently using this library in an aws lambda function where size is important.

**Comment by gajus** [comment]
Of course
