### ISSUE TITLE
calling `server.close` immediately vs later

### ISSUE THREAD

**Issue by bahtou** [gajus/http-terminator#35]
noob question

I'm trying to rampup on the Node.js server internals. I noticed that in the code base you call the `server.close` well after you being to close/destroy connections: https://github.com/gajus/http-terminator/blob/master/src/factories/createInternalHttpTerminator.ts#L154

From the documentation on `server.close` https://nodejs.org/dist/latest-v17.x/docs/api/net.html#serverclosecallback 
> Stops the server from accepting new connections and keeps existing connections.

Wouldn't you want to call this first to stop accepting new connections and then perform the closing/destroying of any socket that is left? Also, since `server.close` stops accepting new connections `connections` event wouldn't be emitted any more, right? So having the following:
```
if (terminating) {
      socket.destroy();
    }
```
in the `connection` event handler wouldn't be needed?

I think I'm overlooking something but can't seem to figure it out.

**Comment by gajus** [comment]
This should explain it

https://github.com/gajus/lightship#add-a-delay-before-stop-handling-incoming-requests
