### ISSUE TITLE
Dropped support for node v12

### ISSUE THREAD

**Issue by sigurdga** [gajus/http-terminator#38]
The most recent commit (4b8336b) mentions dropping support for nodejs 10, but it also sets `engine >= 14`. Is this intentional?

Not that it needs to matter, but the most recent and the next Ubuntu is still on v12. For me, it is just inconvenient and no big deal, but I still wanted to check if it was intentional.

Thanks for your great packages, BTW!

**Comment by gajus** [comment]
This was intentional. v12 is no longer under active maintenance.
