### ISSUE TITLE
Grace period doesn't seem apply to secure connections

### ISSUE THREAD

**Issue by pbharat84** [gajus/http-terminator#9]
Looking at the code it seems the grace period is only applied for http sockets and not for https. Is that the case or am I missing something ?

**Comment by gajus** [comment]
If you contribute a failing test case, I will take a look.

**Comment by pbharat84** [comment]
I don't have a test case as such, but referring to this part in the code felt that might be the case 
`if (sockets.size) {
      await delay(configuration.gracefulTerminationTimeout);

      for (const socket of sockets) {
        destroySocket(socket);
      }
    }`

This is in createInternalHttpTerminator.js under terminate function.

**Comment by pbharat84** [comment]
Found one more place where this seems to be an issue

`const destroySocket = (socket) => {
    socket.destroy();
    sockets.delete(socket);
  };`

In destroySocket only sockets set is considered. But this function is being called while trying to destroy sockets from secureSocket set as well.

**Comment by gajus** [comment]
Sounds like you are onto something. If you end up writing a PR, I sure will review it.
